services:

  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    container_name: template-postgres
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-template}
      POSTGRES_USER: ${POSTGRES_USER:-administrador}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-administrador}
      PGDATA: /var/lib/postgresql/18/docker
    volumes:
      - postgres-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-administrador} -d ${POSTGRES_DB:-template}"]
      interval: 10s
      timeout: 5s
      retries: 5

  wildfly:
    build:
      context: ./wildfly
      dockerfile: Dockerfile
    container_name: template-wildfly
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "${WILDFLY_HTTP_PORT:-8080}:8080"
      - "${WILDFLY_MANAGEMENT_PORT:-9990}:9990"
    environment:
      WILDFLY_ADMIN_USER: ${WILDFLY_ADMIN_USER:-admin}
      WILDFLY_ADMIN_PASSWORD: ${WILDFLY_ADMIN_PASSWORD:-admin}



volumes:
  postgres-data:
