version: "3.7"
services:
  # Balancer
  balancer:
    image: template-nginx:latest
    container_name: template-balancer
    hostname: template-balancer
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app-server
    volumes:
      - balancer-logs:/var/log/nginx
    networks:
      - template-network

  # Application Server
  app-server:
    image: template-tomcat:latest
    container_name: template-server
    hostname: template-server
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - database
    volumes:
      - server-logs:/usr/local/tomcat/logs
    networks:
      - template-network
  
  #Database
  database:
    image: template-postgresql:latest
    container_name: template-database
    hostname: template-database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=administrator
      - POSTGRES_PASSWORD=template2022
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - database-data:/var/lib/postgresql/data
      - database-conf:/etc/postgresql
      - database-log:/var/log/postgresql
    networks:
      - template-network
  
# Networks
networks:
  template-network:
    driver: bridge

# Volumes
volumes:
  balancer-logs:
    driver: local
  server-logs:
    driver: local
  database-data:
    driver: local
  database-conf:
    driver: local
  database-log: 
    driver: local
    