services:

  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    container_name: template-postgres
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-template}
      POSTGRES_USER: ${POSTGRES_USER:-administrador}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-administrador}
      PGDATA: /var/lib/postgresql/18/docker
    volumes:
      - postgres-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-administrador} -d ${POSTGRES_DB:-template}"]
      interval: 10s
      timeout: 5s
      retries: 5

  wildfly:
    build:
      context: ./wildfly
      dockerfile: Dockerfile
    container_name: template-wildfly
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "${WILDFLY_HTTP_PORT:-8080}:8080"
      - "${WILDFLY_MANAGEMENT_PORT:-9990}:9990"
    environment:
      WILDFLY_ADMIN_USER: ${WILDFLY_ADMIN_USER:-admin}
      WILDFLY_ADMIN_PASSWORD: ${WILDFLY_ADMIN_PASSWORD:-admin}

  openproject:
    build:
      context: ./openproyect
      dockerfile: Dockerfile
    container_name: template-openproject
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "${OPENPROJECT_PORT:-8088}:80"
    environment:
      OPENPROJECT_HTTPS: ${OPENPROJECT_HTTPS:-false}
      OPENPROJECT_HOST__NAME: ${OPENPROJECT_HOST_NAME:-localhost:8088}
      SECRET_KEY_BASE: ${OPENPROJECT_SECRET_KEY_BASE:-44b7c614a9de2fb7325a7cab4b94fe9efeb541c1c1275c7ca816e950d0e02d24eced99de0ec51cacf65bee4e8982fe2c8bc4673296a7678ece415fcbccdcbf54}
      OPENPROJECT_RAILS__CACHE__STORE: ${OPENPROJECT_RAILS_CACHE_STORE:-memcache}
      DATABASE_URL: "postgres://${POSTGRES_USER:-administrador}:${POSTGRES_PASSWORD:-administrador}@postgres:5432/${OPENPROJECT_DB:-openproject}"
    volumes:
      - openproject-assets:/var/openproject/assets

volumes:
  postgres-data:
  openproject-assets:


