insert into Report (id, name, description) values (report_seq.nextval, 'Report 01', 'Description of Report 01');
insert into Report (id, name, description) values (report_seq.nextval, 'Report 02', 'Description of Report 02');
insert into Report (id, name, description) values (report_seq.nextval, 'Report 03', 'Description of Report 03');
insert into Report (id, name, description) values (report_seq.nextval, 'Report 04', 'Description of Report 04');
insert into Report (id, name, description) values (report_seq.nextval, 'Report 05', 'Description of Report 05');
insert into Report (id, name, description) values (report_seq.nextval, 'Report 06', 'Description of Report 06');
insert into Report (id, name, description) values (report_seq.nextval, 'Report 07', 'Description of Report 07');
insert into Report (id, name, description) values (report_seq.nextval, 'Report 08', 'Description of Report 08');
insert into Report (id, name, description) values (report_seq.nextval, 'Report 09', 'Description of Report 09');
insert into Report (id, name, description) values (report_seq.nextval, 'Report 10', 'Description of Report 10');
insert into Report (id, name, description) values (report_seq.nextval, 'Report 11', 'Description of Report 11');
insert into Report (id, name, description) values (report_seq.nextval, 'Report 12', 'Description of Report 12');
insert into Report (id, name, description) values (report_seq.nextval, 'Report 13', 'Description of Report 13');
insert into Report (id, name, description) values (report_seq.nextval, 'Report 14', 'Description of Report 14');
insert into Report (id, name, description) values (report_seq.nextval, 'Report 15', 'Description of Report 15');
insert into Report (id, name, description) values (report_seq.nextval, 'Report 16', 'Description of Report 16');
insert into Report (id, name, description) values (report_seq.nextval, 'Report 17', 'Description of Report 17');
insert into Report (id, name, description) values (report_seq.nextval, 'Report 18', 'Description of Report 18');
insert into Report (id, name, description) values (report_seq.nextval, 'Report 19', 'Description of Report 19');
insert into Report (id, name, description) values (report_seq.nextval, 'Report 20', 'Description of Report 20');
insert into Report (id, name, description) values (report_seq.nextval, 'Report 21', 'Description of Report 21');
insert into Report (id, name, description) values (report_seq.nextval, 'Report 22', 'Description of Report 22');

insert into Action (id, name, description) values (action_seq.nextval, 'REPORT_C', 'Report - Create');
insert into Action (id, name, description) values (action_seq.nextval, 'REPORT_R', 'Report - Read');
insert into Action (id, name, description) values (action_seq.nextval, 'REPORT_U', 'Report - Update');
insert into Action (id, name, description) values (action_seq.nextval, 'REPORT_D', 'Report - Delete');
insert into Action (id, name, description) values (action_seq.nextval, 'REPORT_E', 'Report - Execute');

insert into Profile (id, name, description) values (profile_seq.nextval, 'ADMINISTRATOR', 'Administration');
insert into Profile (id, name, description) values (profile_seq.nextval, 'SUPPORT', 'Support');
insert into Profile (id, name, description) values (profile_seq.nextval, 'USER', 'User');
insert into Profile (id, name, description) values (profile_seq.nextval, 'MANAGER', 'Manager');

insert into Profile_Action (action_id, profile_id) values (1, 1);
insert into Profile_Action (action_id, profile_id) values (2, 1);
insert into Profile_Action (action_id, profile_id) values (3, 1);
insert into Profile_Action (action_id, profile_id) values (4, 1);
insert into Profile_Action (action_id, profile_id) values (5, 1);
insert into Profile_Action (action_id, profile_id) values (5, 3);

insert into User (id, username, password, profile_id) values (user_seq.nextval, 'admin', 'admin', 1);
insert into User (id, username, password, profile_id) values (user_seq.nextval, 'support', 'support', 2);
insert into User (id, username, password, profile_id) values (user_seq.nextval, 'user01', 'user01', 3);

insert into Trace (id, datetime, message) values (trace_seq.nextval, CURRENT_TIMESTAMP(), 'maPY4qDUNiY4aW38hmXUxaoCnmSft25U2waBPGAMwTDg2eUpdcmgnl7y7MJu');
insert into Trace (id, datetime, message) values (trace_seq.nextval, CURRENT_TIMESTAMP(), 'gnl9hrknzQCU9zrh8g71nDNSq3oTMseZ6h7uKH3EmkbcMnZttnQMzpzuicLr');
insert into Trace (id, datetime, message) values (trace_seq.nextval, CURRENT_TIMESTAMP(), 'SiOiAnqotZXbL1Vj0QJJ8ZCnpKFhziCjRNaqHYUIxYhzJIIkw1qJ19IIHEX5');
insert into Trace (id, datetime, message) values (trace_seq.nextval, CURRENT_TIMESTAMP(), '5XCZqRM5D4GzRGRtKkYj7aSEiu7yIKo9KvELURnO5na3mUBAOcHJBBK5pczd');
insert into Trace (id, datetime, message) values (trace_seq.nextval, CURRENT_TIMESTAMP(), 'pJm1Cm0WxK8fv6yGcLfWxrMvvqBmujwXEb6FwzdHM6clOLnVWewesyoatCVn');
insert into Trace (id, datetime, message) values (trace_seq.nextval, CURRENT_TIMESTAMP(), 'vBAeYyboWe3PTk059nPez6bZviPFqhbYZNlxpibsnX6BI0erujpjnPjCbA9p');
insert into Trace (id, datetime, message) values (trace_seq.nextval, CURRENT_TIMESTAMP(), 'NHI3F0Bzg2u9HrBMdD7bju7fweu9LB2aHvLVo0IY4njm3Pq1XZdxdvng1exw');
insert into Trace (id, datetime, message) values (trace_seq.nextval, CURRENT_TIMESTAMP(), 'BIEdCpuhbfOhSBfUB3vxQGVtsMuXK07R0vuQyIJVeyHQo2Foz8cAWR4mBa7S');
insert into Trace (id, datetime, message) values (trace_seq.nextval, CURRENT_TIMESTAMP(), 'YqFn6hlbEBBUEf7pJqP6kKIasqY39Sh0mnFzyDLeugkDHhXfrDRC0HQkCGoS');
insert into Trace (id, datetime, message) values (trace_seq.nextval, CURRENT_TIMESTAMP(), 'dSpLCF8XuY5DZtbSDFbDTJ2B3hJcEOQFC3U8OiE3N7N7hWesBih1jNYzIv1G');
insert into Trace (id, datetime, message) values (trace_seq.nextval, CURRENT_TIMESTAMP(), 'GOKB1Wm4AQfvOP4Wlyt9trGqBsV9h5kO1jPsc3MkUwizBWip0owpLOFItdYf');
insert into Trace (id, datetime, message) values (trace_seq.nextval, CURRENT_TIMESTAMP(), '33PJxA2caAA7IMo0K6B70vYmcPUaYxpblK1XsV2oV8cY7Gs9sMfyGHAXYh6r');
insert into Trace (id, datetime, message) values (trace_seq.nextval, CURRENT_TIMESTAMP(), 'oxrUMs32HBAUVkmtoRpAQB9Yxucx5SpsXLntdkw8gjvm7wQ8bEgSku4mvhW2');
insert into Trace (id, datetime, message) values (trace_seq.nextval, CURRENT_TIMESTAMP(), 'CjMmKcDulCB4WkdR1Bd00p0Jw3kewbKszRZk21Af2MoVdlFzJDoiVkNcHvYb');
insert into Trace (id, datetime, message) values (trace_seq.nextval, CURRENT_TIMESTAMP(), 'ksN4pa7ACT8vHzH8lJMD83YSRcra5uMI1GkY9BXFmRViqJP7HciHo2C9TCwi');
insert into Trace (id, datetime, message) values (trace_seq.nextval, CURRENT_TIMESTAMP(), 'Dhz8JnZiZHs6NVAuduTGEGHV6vLQavF36gTXczftGtoiaxFWtpcsxm3lmdNc');
insert into Trace (id, datetime, message) values (trace_seq.nextval, CURRENT_TIMESTAMP(), 'bxpYryqZqU2vBlcbEZCwdLYquIK5fE09mHPMI5Ajgwo4q4adQz6acg3JiMrQ');
insert into Trace (id, datetime, message) values (trace_seq.nextval, CURRENT_TIMESTAMP(), 'Br6w5vuqs4hcNTke6CDSrgosWFuXw5FMAa6IA7leOYAKtpAmUzduPd7bov0k');
insert into Trace (id, datetime, message) values (trace_seq.nextval, CURRENT_TIMESTAMP(), 'Ue2ip7haQVDOzhnSP9gajtJdlHHv1SDRCYaksH5swcwmH79wHlJYV9BlNWu6');
insert into Trace (id, datetime, message) values (trace_seq.nextval, CURRENT_TIMESTAMP(), 'xuhBVR8g3G6VmU8YWDaXzBcIxhnHlz2neGtO01Vr2TBSOvCMkTxdssRku7F5');
insert into Trace (id, datetime, message) values (trace_seq.nextval, CURRENT_TIMESTAMP(), 'JnH2x2NYmfbbCbbhHWPEkQUZ8iqK7kqLwjpg6HancDsllWYDLePLSomJefU9');
insert into Trace (id, datetime, message) values (trace_seq.nextval, CURRENT_TIMESTAMP(), 'MlnnAqdfkrrIBN6mXmcYf382WYROldGU5zgUU0hXRS1JOiqhyNkOZAbJcU30');
insert into Trace (id, datetime, message) values (trace_seq.nextval, CURRENT_TIMESTAMP(), 'trGsQa3BOlcP59xYAKxYe8CQTcKB1diMoxJbMZUvpm8cunIiFeEPsp8pdenN');
insert into Trace (id, datetime, message) values (trace_seq.nextval, CURRENT_TIMESTAMP(), 'iujW6V6wK730cremIzJ4gRC4oDqAeQVzvb95iSUdmd3jrT46hId9P4hb312G');
insert into Trace (id, datetime, message) values (trace_seq.nextval, CURRENT_TIMESTAMP(), 'sXNK4ZwRMe0eBi6yrHGTnyqUPvv8aLlg9fyt6YQLo3L9vzfbhjPBueHfqyZh');
insert into Trace (id, datetime, message) values (trace_seq.nextval, CURRENT_TIMESTAMP(), 'dvYRjIW1MPd9yi6Vn6UVTpVKJbdEJB5xgWLWF0LhQz0c3nxmT15POaFEeniT');
insert into Trace (id, datetime, message) values (trace_seq.nextval, CURRENT_TIMESTAMP(), 'UFzqhF9m4Z7KfXi268kt0WnfAbIRZzbXaAOb1nJ6ge0lJS6o8vIBqgxKY3o2');
insert into Trace (id, datetime, message) values (trace_seq.nextval, CURRENT_TIMESTAMP(), 'wwS2ZDdPDQUnAPQxW00RW9t9toDBGtbWFKrhEAGTp5Bflg9qRERrGDJ0VtjQ');
insert into Trace (id, datetime, message) values (trace_seq.nextval, CURRENT_TIMESTAMP(), 'OTsKkIHq9W5ZMnsnCLWNNN8OXG8x3BHdxvqCN9u1ZPrZljS9vpeyAcdUUqbm');
insert into Trace (id, datetime, message) values (trace_seq.nextval, CURRENT_TIMESTAMP(), 'YgFhtbru0xIHMQrMHDcOLCNtskaV9dtQVBDWcNFJjwniWgWe38TGnbiPMWst');
insert into Trace (id, datetime, message) values (trace_seq.nextval, CURRENT_TIMESTAMP(), 'GCOqIR1URwywuzlor3YP6JrkafYlBIU5lA7kQ7yArqnmi6Yp2ZBUNLZbOqKL');
insert into Trace (id, datetime, message) values (trace_seq.nextval, CURRENT_TIMESTAMP(), 'sWhvcIRWYHWi1jIVSnkpGGKwVPy4haE95hABZw9pecGQ7Ph6h2MIEVOMgXsM');
insert into Trace (id, datetime, message) values (trace_seq.nextval, CURRENT_TIMESTAMP(), 'OsZsBV3J7fldmAsMDiWOUNr4E5HJGOHVjKRe32kP5JDRCV4vY6rd15WCn5bt');
insert into Trace (id, datetime, message) values (trace_seq.nextval, CURRENT_TIMESTAMP(), 'Fd6gVRPqbN7VWcXfI87PWHPKzMKzjn6cb38QaKreKGenNWmpxPsnIZGpAbQl');
insert into Trace (id, datetime, message) values (trace_seq.nextval, CURRENT_TIMESTAMP(), 'M1PNjxfkdxDrZio9JRaCivIET0CxpLF2k1Uemm8x9Wlfl4k6l4Ex3em5RxuA');
insert into Trace (id, datetime, message) values (trace_seq.nextval, CURRENT_TIMESTAMP(), '9xv26gCIgDXVYioAiupEKhEfYT1Cj26I3zqjgdIyA9v6gSlanySsHz6EjxHN');
insert into Trace (id, datetime, message) values (trace_seq.nextval, CURRENT_TIMESTAMP(), 'EfptdiqJOO0TgWquko3Tx4Zw3egPiJ5yjW1vuClXCNiLMHTsKLz4CMHEFat7');
insert into Trace (id, datetime, message) values (trace_seq.nextval, CURRENT_TIMESTAMP(), '3xmPAfnZX6Ymz95qndMXPScTnGbhOsENDGm28SHZK3ChE0PckAxL2IjUVbBv');
insert into Trace (id, datetime, message) values (trace_seq.nextval, CURRENT_TIMESTAMP(), 'kv3P5iToCqTFltLhalC8aKQ2orCsDlELYibc1HGx8fq5kZanAna7zWzsmvI3');
insert into Trace (id, datetime, message) values (trace_seq.nextval, CURRENT_TIMESTAMP(), 'wKer81BQFQUY1r0GKSdfKQPws6dYmmMwu9IJU99o1rnA1rhXUkomiIetl9x5');
insert into Trace (id, datetime, message) values (trace_seq.nextval, CURRENT_TIMESTAMP(), '72cjWPOtAtOjuBvOk9yEeey8qRsYPsMVMkh7uvLe41sYKoNMvIyv9UprpmGb');
insert into Trace (id, datetime, message) values (trace_seq.nextval, CURRENT_TIMESTAMP(), '1PabnXdHMfxWMfldViXqattyYwNMe26bVU6h0fYhwtPRzgsT4iWyJ83sRtW7');
insert into Trace (id, datetime, message) values (trace_seq.nextval, CURRENT_TIMESTAMP(), '5ESoXdO0BJgDvmZsFycJ5fdNhqwfp8e6dtAKXYGWZbBQ5HldOFJ18OLAlq6H');
insert into Trace (id, datetime, message) values (trace_seq.nextval, CURRENT_TIMESTAMP(), 'ZKURTckv85rxZxyLvYSKvwZN9cqfq0QNdnHFu9SpsR0Fz6ZbpfHlCXHdD0ZS');
insert into Trace (id, datetime, message) values (trace_seq.nextval, CURRENT_TIMESTAMP(), 'OXS1AhhWc3MlR03sVvh7zHLA6BJg3KTiekcaE2P5Q5lPmOQeewXeoCNPZFKr');
insert into Trace (id, datetime, message) values (trace_seq.nextval, CURRENT_TIMESTAMP(), 'oocmlhNCgx10CSx3xuhJx3S02NwyePdRJBogOyIZjASWpSkUjyt15azWX2bP');
insert into Trace (id, datetime, message) values (trace_seq.nextval, CURRENT_TIMESTAMP(), '4X43vJ4azZghLhR7pTPfEOiEUOtu4Ek1XIOkduY6XY7GB8qA6nZirOYm75hu');
insert into Trace (id, datetime, message) values (trace_seq.nextval, CURRENT_TIMESTAMP(), 'RrIOi96F18Okd28npIylksQc99wFG2T7JZhM0ENvuSZxVaqoUTStQWi1FxHU');
insert into Trace (id, datetime, message) values (trace_seq.nextval, CURRENT_TIMESTAMP(), '2GPGgsOJ8TNKCFaP1zwnbpTGOFohY8xJFOtZjhCKLxxqHj9ExfrS24bj2WEm');
insert into Trace (id, datetime, message) values (trace_seq.nextval, CURRENT_TIMESTAMP(), '8NwBiQjUeTU5x30x5oO8rj3TUOHlvsmIMTunW1eu7mBwELrJyYjy9oyl6g2O');
insert into Trace (id, datetime, message) values (trace_seq.nextval, CURRENT_TIMESTAMP(), 'N7zXdZiHVWLkuNY3PR6iTocR7CjWvY6sDgRzlzBOgwLOJRygoC3CKqBoEpMM');
insert into Trace (id, datetime, message) values (trace_seq.nextval, CURRENT_TIMESTAMP(), '5MBfVSZpTytIKFrf52bxlPlEG0eb164GKCzwwUFy7pcQpEuFB6IqWgsX6mmN');
insert into Trace (id, datetime, message) values (trace_seq.nextval, CURRENT_TIMESTAMP(), 'lOg0QkaJbntdwaRbpnRmuEFBPyapv8AjolHZt9N7Eni1yAHTbuhprGQ2xj0o');
insert into Trace (id, datetime, message) values (trace_seq.nextval, CURRENT_TIMESTAMP(), 'hxhF9IBij3ZK6nrp5Xke0g4EVmfo40PhOp8E3g69CBWhAeXamWEpdYTCVYWe');
insert into Trace (id, datetime, message) values (trace_seq.nextval, CURRENT_TIMESTAMP(), 'PYFg2402aGgeTmq1waLFC52Q34C7NtAGNO5SR6KfPxfnDoozGyaFppMEAFTz');
insert into Trace (id, datetime, message) values (trace_seq.nextval, CURRENT_TIMESTAMP(), '54C4uaeNAjNmpCEJrWPthjrLE5ivAD1AlGypzVGvrTjW5lvh42NW1TI2wTlh');
insert into Trace (id, datetime, message) values (trace_seq.nextval, CURRENT_TIMESTAMP(), 'VlnbehOa72X9oiL0Rp45QA9RPrTR8SqGVUY1j66d0GhkswN5Krffze5979hx');
insert into Trace (id, datetime, message) values (trace_seq.nextval, CURRENT_TIMESTAMP(), 'meOzud6jPLM1BMq3eW1FEMbTaBaMOl1n6tLcpL8HyG1AAssmGEVfKMdjYOdW');
insert into Trace (id, datetime, message) values (trace_seq.nextval, CURRENT_TIMESTAMP(), 'cOZBE3ROTgem8CU6BIpC30l53QFM6JVbyddB1myr2vWvV9fhAZyIEik2thE6');
insert into Trace (id, datetime, message) values (trace_seq.nextval, CURRENT_TIMESTAMP(), 'KZqZ35YOAzbkQTYqr0GluZL8yaLYv5qnnbZNOlibL8qRiDMQCRnDnxF9yqrj');

insert into Task (id, name, description) values (task_seq.nextval, 'DUMMY', 'Description of Task');